// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OddOneOut.Data;

#nullable disable

namespace OddOneOut.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251229102706_gamecards5")]
    partial class gamecards5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardSetWordCard", b =>
                {
                    b.Property<Guid>("CardSetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WordCardsId")
                        .HasColumnType("uuid");

                    b.HasKey("CardSetId", "WordCardsId");

                    b.HasIndex("WordCardsId");

                    b.ToTable("CardSetWordCard");
                });

            modelBuilder.Entity("OddOneOut.Data.CardSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CardSet");
                });

            modelBuilder.Entity("OddOneOut.Data.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Clue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("ClueGiver")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OddOneOutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CardSetId");

                    b.HasIndex("OddOneOutId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("OddOneOut.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OddOneOut.Data.WordCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WordCard");
                });

            modelBuilder.Entity("CardSetWordCard", b =>
                {
                    b.HasOne("OddOneOut.Data.CardSet", null)
                        .WithMany()
                        .HasForeignKey("CardSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OddOneOut.Data.WordCard", null)
                        .WithMany()
                        .HasForeignKey("WordCardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OddOneOut.Data.Game", b =>
                {
                    b.HasOne("OddOneOut.Data.CardSet", "CardSet")
                        .WithMany("Games")
                        .HasForeignKey("CardSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OddOneOut.Data.WordCard", "OddOneOut")
                        .WithMany()
                        .HasForeignKey("OddOneOutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardSet");

                    b.Navigation("OddOneOut");
                });

            modelBuilder.Entity("OddOneOut.Data.CardSet", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
